### ISSUE TITLE
Unknown errors 551 and 550

### ISSUE THREAD

**Issue by Remix2100** [cognalys/cogdemo#1]
I'm using cognalys sdk in my app for user verification but i get the errors 551 and 550 which are not listed on their site and I don't know what are they, here is the code I use:

Cognalys.verifyMobileNumber(SignupActivity.this,"token",
                        "id","number",
                        new VerificationListner() {

```
                @Override
                public void onVerificationStarted() {

                    Toast.makeText(getApplicationContext(), "Started", Toast.LENGTH_LONG).show(); 

                }

                @Override
                public void onVerificationFailed(ArrayList<String> errorList) {

                    for (String error : errorList) {
                        Log.d("abx", "error:"+error);
                    }
                    Toast.makeText(getApplicationContext(), "Failed", Toast.LENGTH_LONG).show();

                }

                @Override
                public void onVerificationSuccess() {

                    Toast.makeText(getApplicationContext(), "Signed up successfully !", Toast.LENGTH_SHORT).show();
                    Intent intent = new Intent(SignupActivity.this, SetPictures.class);
                    startActivity(intent);
                    finish();

                }
            });
```

instead of number I put my number from my code, I get the missed call but the toast "failed" shows up with error 550 in my log, can anybody tell me what does it mean?

**Comment by cognalys** [comment]
Hi @Remix2100 

Please find the open source of the cognalys mobile number verification library for android  from the link below

https://github.com/cognalys/cognalys-android-library

You can explore the code of the library and can edit  the  library according to your requirement.

best regards
Sam
